import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;


// loadDashboardCounts();
// loadInventoryOverview();



/*

 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Administrator
 */
public class AdminDashboardFrame extends javax.swing.JFrame {
    
   

    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminDashboardFrame.class.getName());

    /**
     * Creates new form AdminDashboardFrame
     */
    public AdminDashboardFrame() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        loadDashboardCounts();
        loadInventoryOverview();
        loadOrdersOverview();

        
        

        
        loadLogo();
        
        
    }
 

  private void loadOrdersOverview() {
    try (Connection conn = DBConnection.getConnection()) {

        String sql = "SELECT id, customer_name, address, product_name, quantity, status FROM orders";
        PreparedStatement pst = conn.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();

        DefaultTableModel model =
            (DefaultTableModel) jTable2.getModel();

        model.setRowCount(0); // clear old rows

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("id"),
                rs.getString("customer_name"),
                rs.getString("address"),
                rs.getString("product_name"),
                rs.getInt("quantity"),
                rs.getString("status")
            });
        }

    } catch (Exception e) {
        e.printStackTrace();
    }
}
  
    
 private void loadInventoryOverview() {
    try (Connection conn = DBConnection.getConnection()) {

        String sql = "SELECT id, name, stock, price FROM inventory";
        PreparedStatement pst = conn.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();

        DefaultTableModel model =
            (DefaultTableModel) inventoryOverviewTable.getModel();

        model.setRowCount(0); // clear old rows

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("id"),
                rs.getString("name"),
                rs.getInt("stock"),
                rs.getDouble("price")
            });
        }

    } catch (Exception e) {
        e.printStackTrace();
    }
}
   
private void loadLogo() {
    jLabel1.setSize(240, 100); // 🔥 2x size

    ImageIcon icon = new ImageIcon(
        getClass().getResource("/logo.png") // change name if needed
    );

    Image img = icon.getImage();
    Image scaledImg = img.getScaledInstance(
        240, 100, Image.SCALE_SMOOTH
    );

    jLabel1.setIcon(new ImageIcon(scaledImg));
    jLabel1.setText("");
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navBarPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        inventoryButton = new javax.swing.JButton();
        ordersButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        welcomeLabel = new javax.swing.JLabel();
        cardsPanel = new javax.swing.JPanel();
        InventoryCard = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        inventoryCountLabel = new javax.swing.JLabel();
        OrderCard = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        ordersCountLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tablePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        inventoryOverviewTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Dashboard");
        setMaximumSize(new java.awt.Dimension(900, 600));
        setMinimumSize(new java.awt.Dimension(900, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        navBarPanel.setBackground(new java.awt.Color(76, 175, 80));
        navBarPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        navBarPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.png"))); // NOI18N
        navBarPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 240, 40));

        inventoryButton.setBackground(new java.awt.Color(0, 204, 102));
        inventoryButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        inventoryButton.setText("Inventory");
        inventoryButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        inventoryButton.setContentAreaFilled(false);
        inventoryButton.setFocusPainted(false);
        inventoryButton.addActionListener(this::inventoryButtonActionPerformed);
        navBarPanel.add(inventoryButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 90, 40));

        ordersButton.setBackground(new java.awt.Color(0, 204, 102));
        ordersButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ordersButton.setText("Orders");
        ordersButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ordersButton.setContentAreaFilled(false);
        ordersButton.setFocusPainted(false);
        ordersButton.addActionListener(this::ordersButtonActionPerformed);
        navBarPanel.add(ordersButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, 80, 40));

        logoutButton.setBackground(new java.awt.Color(0, 204, 102));
        logoutButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        logoutButton.setText("Logout");
        logoutButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        logoutButton.setContentAreaFilled(false);
        logoutButton.setFocusPainted(false);
        logoutButton.addActionListener(this::logoutButtonActionPerformed);
        navBarPanel.add(logoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 20, 90, 40));

        getContentPane().add(navBarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 70));

        mainPanel.setBackground(new java.awt.Color(244, 246, 248));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcomeLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        welcomeLabel.setText("Welcome,");
        mainPanel.add(welcomeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 300, 30));

        cardsPanel.setBackground(new java.awt.Color(255, 255, 255));
        cardsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        InventoryCard.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        InventoryCard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setText("Total Inventory");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        InventoryCard.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 40));

        inventoryCountLabel.setBackground(new java.awt.Color(0, 204, 102));
        inventoryCountLabel.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        inventoryCountLabel.setForeground(new java.awt.Color(0, 204, 102));
        inventoryCountLabel.setText("15");
        InventoryCard.add(inventoryCountLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));

        cardsPanel.add(InventoryCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 120));

        OrderCard.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        OrderCard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel5.setText("Total Orders");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        OrderCard.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 40));

        ordersCountLabel.setBackground(new java.awt.Color(0, 204, 102));
        ordersCountLabel.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        ordersCountLabel.setForeground(new java.awt.Color(0, 204, 102));
        ordersCountLabel.setText("7");
        OrderCard.add(ordersCountLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));

        cardsPanel.add(OrderCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 400, 120));

        mainPanel.add(cardsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 840, 140));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setText("Admin!");
        mainPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, 30));

        tablePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inventoryOverviewTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Product ID", "Name", "Stock", "Price"
            }
        ));
        jScrollPane1.setViewportView(inventoryOverviewTable);

        tablePanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 400, 240));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", "", null, "", "", ""},
                {"", "", null, "", "", ""},
                {"", "", null, "", "", null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Order ID", "Customer", "Address", "Product", "Qty", "Status"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        tablePanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 400, 240));

        mainPanel.add(tablePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 840, 260));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setText("Inventory Overview");
        mainPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setText("Orders Overview");
        mainPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, -1, -1));

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 900, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void loadDashboardCounts() {
    try (Connection conn = DBConnection.getConnection()) {

        // Inventory count
        String inventorySql = "SELECT COUNT(*) FROM inventory";
        PreparedStatement pst1 = conn.prepareStatement(inventorySql);
        ResultSet rs1 = pst1.executeQuery();
        if (rs1.next()) {
            inventoryCountLabel.setText(rs1.getInt(1) + "");
        }

        // Orders count
        String ordersSql = "SELECT COUNT(*) FROM orders";
        PreparedStatement pst2 = conn.prepareStatement(ordersSql);
        ResultSet rs2 = pst2.executeQuery();
        if (rs2.next()) {
            ordersCountLabel.setText(rs2.getInt(1) + "");
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error loading dashboard data");
        e.printStackTrace();
    }
}

    private void inventoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventoryButtonActionPerformed
    // Open InventoryFrame
    InventoryFrame inventory = new InventoryFrame();
    
    inventory.setVisible(true);

    // Close the current AdminDashboardFrame
    this.dispose();    // TODO add your handling code here:
    }//GEN-LAST:event_inventoryButtonActionPerformed

    private void ordersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordersButtonActionPerformed
    OrdersFrame orders = new OrdersFrame();  // open OrdersFrame
    
    orders.setVisible(true);
    orders.setLocationRelativeTo(null);       // center the window
    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_ordersButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
    AdminLoginFrame login = new AdminLoginFrame();
    
    login.setVisible(true);
    login.setLocationRelativeTo(null); // center screen
    this.dispose(); // close dashboard    // TODO add your handling code here:
    }//GEN-LAST:event_logoutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminDashboardFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel InventoryCard;
    private javax.swing.JPanel OrderCard;
    private javax.swing.JPanel cardsPanel;
    private javax.swing.JButton inventoryButton;
    private javax.swing.JLabel inventoryCountLabel;
    private javax.swing.JTable inventoryOverviewTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton logoutButton;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel navBarPanel;
    private javax.swing.JButton ordersButton;
    private javax.swing.JLabel ordersCountLabel;
    private javax.swing.JPanel tablePanel;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}