import javax.swing.*;
import java.awt.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Administrator
 */
public class CartFrame extends javax.swing.JFrame {
    
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CartFrame.class.getName());
    
    
   private javax.swing.JPanel cartItemsPanel;
   
   
    /**
     * Creates new form CartFrame
     */
    public CartFrame() {
     initComponents();
     
     setLocationRelativeTo(null);
     
     
     cartItemsPanel = new JPanel();
cartItemsPanel.setLayout(null); // manual positioning
cartItemsPanel.setBounds(40, 10, 530, 270);
cartItemsPanel.setBackground(Color.WHITE);

 getContentPane().add(cartItemsPanel,
        new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 530, 270));

loadCartManual();
}

  // add this to your variable declarations
   
private void loadCartManual() {
    cartItemsPanel.removeAll(); // clear old items
    double subtotal = 0;

    int yPosition = 10; // start y position for first item

    for (Product p : Cart.getItems()) {
        JPanel itemPanel = new JPanel();
        itemPanel.setLayout(null);
        itemPanel.setBounds(0, yPosition, 530, 40); // width = 530, height = 40
        itemPanel.setBackground(new Color(240, 240, 240));

        JLabel lblName = new JLabel(p.getName());
        lblName.setBounds(10, 5, 250, 30);
        itemPanel.add(lblName);

        JLabel lblPrice = new JLabel("₱ " + p.getPrice());
        lblPrice.setBounds(270, 5, 100, 30);
        itemPanel.add(lblPrice);

        JButton btnRemove = new JButton("Remove");
        btnRemove.setBounds(380, 5, 100, 30);
        btnRemove.addActionListener(e -> {
            Cart.getItems().remove(p);
            loadCartManual(); // refresh the cart display
        });
        itemPanel.add(btnRemove);

        cartItemsPanel.add(itemPanel);

        yPosition += 50; // move down for next item
        subtotal += p.getPrice();
    }

    cartItemsPanel.revalidate();
    cartItemsPanel.repaint();

    double shipping = 500;
    double total = subtotal + shipping;

    lblSubtotal.setText("₱ " + subtotal);
    lblShipping.setText("₱ " + shipping);
    lblTotal.setText("₱ " + total);
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTotal = new javax.swing.JLabel();
        lblSubtotal = new javax.swing.JLabel();
        lblShipping = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Your Cart");
        setPreferredSize(new java.awt.Dimension(600, 400));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTotal.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTotal.setText("Total:");
        getContentPane().add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, -1, -1));

        lblSubtotal.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblSubtotal.setText("Subtotal:");
        getContentPane().add(lblSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, -1, -1));

        lblShipping.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblShipping.setText("Shipping:");
        getContentPane().add(lblShipping, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Total:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 153, 204));
        jButton1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Checkout ");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(this::jButton1ActionPerformed);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 280, 120, 50));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Subtotal:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Shipping:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
    if (Cart.getItems().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Your cart is empty!");
        return;
    }

    int confirm = JOptionPane.showConfirmDialog(this, "Confirm checkout?", "Checkout", JOptionPane.YES_NO_OPTION);
    if (confirm != JOptionPane.YES_OPTION) return;

    // Assume we already have customer info
    int customerId = Session.customerId;
String customerName = Session.fullName;
String customerAddress = Session.address;



    try (Connection conn = DBConnection.getConnection()) {

    conn.setAutoCommit(false); // 🔥 start transaction

    String insertSql = "INSERT INTO orders (customer_id, product_id, customer_name, address, product_name, quantity, status) VALUES (?, ?, ?, ?, ?, ?, ?)";
    PreparedStatement insertPst = conn.prepareStatement(insertSql);

    String updateSql = "UPDATE inventory SET stock = stock - ? WHERE id = ?";
    PreparedStatement updatePst = conn.prepareStatement(updateSql);

    for (Product p : Cart.getItems()) {

        int productId = p.getId();   // 🔥 now works
        String productName = p.getName();
        int quantity = 1; // still 1 per click

        // 1️⃣ Insert into orders
        insertPst.setInt(1, customerId);
        insertPst.setInt(2, productId);
        insertPst.setString(3, customerName);
        insertPst.setString(4, customerAddress);
        insertPst.setString(5, productName);
        insertPst.setInt(6, quantity);
        insertPst.setString(7, "Pending");
        insertPst.executeUpdate();

        // 2️⃣ Subtract stock
        updatePst.setInt(1, quantity);
        updatePst.setInt(2, productId);
        updatePst.executeUpdate();
    }
conn.commit();
    // Build receipt
StringBuilder receipt = new StringBuilder();
receipt.append("========================================\n");
receipt.append("       ANGEL FUNERAL SERVICES          \n");
receipt.append("            - CoffinCart -             \n");
receipt.append("========================================\n\n");
receipt.append("Customer : ").append(Session.fullName).append("\n");
receipt.append("Address  : ").append(Session.address).append("\n");
receipt.append("Date     : ").append(new java.util.Date()).append("\n");
receipt.append("\n----------------------------------------\n");
receipt.append("ITEMS ORDERED:\n");
receipt.append("----------------------------------------\n");

double subtotal = 0;
for (Product p : Cart.getItems()) {
    receipt.append(String.format("%-25s  P%.2f%n", p.getName(), p.getPrice()));
    subtotal += p.getPrice();
}

double shipping = 500;
double total = subtotal + shipping;

receipt.append("----------------------------------------\n");
receipt.append(String.format("%-25s  P%.2f%n", "Subtotal:", subtotal));
receipt.append(String.format("%-25s  P%.2f%n", "Shipping Fee:", shipping));
receipt.append("----------------------------------------\n");
receipt.append(String.format("%-25s  P%.2f%n", "TOTAL:", total));
receipt.append("----------------------------------------\n\n");
receipt.append("  Thank you for trusting Angel Funeral  \n");
receipt.append("        Services - CoffinCart           \n");
receipt.append("========================================\n");

// Show receipt popup
javax.swing.JTextArea textArea = new javax.swing.JTextArea(receipt.toString());
textArea.setFont(new java.awt.Font("Courier New", java.awt.Font.PLAIN, 13));
textArea.setEditable(false);
javax.swing.JScrollPane scrollPane = new javax.swing.JScrollPane(textArea);
scrollPane.setPreferredSize(new java.awt.Dimension(420, 450));

javax.swing.JOptionPane.showMessageDialog(
    this,
    scrollPane,
    "Order Receipt - CoffinCart",
    javax.swing.JOptionPane.INFORMATION_MESSAGE
);

Cart.clear();
this.dispose();


} catch (Exception ex) {
    ex.printStackTrace();
    JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
}

    // Optional: Refresh OrdersFrame if open
    OrdersFrame ordersFrame = new OrdersFrame();
    ordersFrame.setVisible(true);
    new CustomerDashboardFrame().setVisible(true);
    this.dispose(); // close cart
   // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CartFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblShipping;
    private javax.swing.JLabel lblSubtotal;
    private javax.swing.JLabel lblTotal;
    // End of variables declaration//GEN-END:variables
}
