import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Administrator
 */

public class InventoryFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InventoryFrame.class.getName());

    /**
     * Creates new form InventoryFrame
     */
    public InventoryFrame() {
    initComponents();
    setLocationRelativeTo(null); // ✅ center this frame too
    setResizable(false);
    inventoryTable.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {},
        new String [] { "Product ID", "Name", "Stock", "Price" }
    ) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    });

    loadInventoryData();
}
 private void loadInventoryData() {
    try (Connection conn = DBConnection.getConnection()) {

        String sql = "SELECT id, name, stock, price FROM inventory";
        PreparedStatement pst = conn.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();

        DefaultTableModel model = (DefaultTableModel) inventoryTable.getModel();
        model.setRowCount(0);

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("id"),
                rs.getString("name"),
                rs.getInt("stock"),
                rs.getDouble("price")
            });
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error loading inventory data");
        e.printStackTrace();
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navBarPanel = new javax.swing.JPanel();
        titleLable = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        contentPanel = new javax.swing.JPanel();
        inventoryScrollPane = new javax.swing.JScrollPane();
        inventoryTable = new javax.swing.JTable();
        sectionLabel = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inventory");
        setMaximumSize(new java.awt.Dimension(900, 600));
        setMinimumSize(new java.awt.Dimension(900, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        navBarPanel.setBackground(new java.awt.Color(76, 175, 80));
        navBarPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleLable.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        titleLable.setForeground(new java.awt.Color(255, 255, 255));
        titleLable.setText("Inventory");
        navBarPanel.add(titleLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 200, 30));

        backButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(this::backButtonActionPerformed);
        navBarPanel.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 20, 70, 30));

        getContentPane().add(navBarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 70));

        contentPanel.setBackground(new java.awt.Color(244, 246, 248));
        contentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inventoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Product ID", "Name", "Stock", "Price"
            }
        ));
        inventoryScrollPane.setViewportView(inventoryTable);

        contentPanel.add(inventoryScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 800, 350));

        sectionLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        sectionLabel.setText("Inventory List");
        contentPanel.add(sectionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 200, 30));

        addButton.setText("Add Product");
        addButton.addActionListener(this::addButtonActionPerformed);
        contentPanel.add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, -1, -1));

        deleteButton.setText("Delete Selected");
        deleteButton.addActionListener(this::deleteButtonActionPerformed);
        contentPanel.add(deleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 460, -1, -1));

        getContentPane().add(contentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 900, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
      // Go back to Dashboard
    AdminDashboardFrame dashboard = new AdminDashboardFrame();
    dashboard.setVisible(true);
    
    // Close InventoryFrame
    this.dispose();  // TODO add your handling code here:
    }//GEN-LAST:event_backButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
    

    String name = JOptionPane.showInputDialog(this, "Enter product name:");
    if (name == null || name.isEmpty()) return;

    String stockStr = JOptionPane.showInputDialog(this, "Enter stock:");
    String priceStr = JOptionPane.showInputDialog(this, "Enter price:");

    try {
        int stock = Integer.parseInt(stockStr);
        double price = Double.parseDouble(priceStr);

        Connection conn = DBConnection.getConnection();
        String sql = "INSERT INTO inventory (name, stock, price) VALUES (?, ?, ?)";
        PreparedStatement pst = conn.prepareStatement(sql);

        pst.setString(1, name);
        pst.setInt(2, stock);
        pst.setDouble(3, price);

        pst.executeUpdate();
        conn.close();

        JOptionPane.showMessageDialog(this, "Product added successfully!");
        loadInventoryData(); // 🔁 refresh table

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Invalid input or database error");
        e.printStackTrace();
    }

   // TODO add your handling code here:
    }//GEN-LAST:event_addButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
    int row = inventoryTable.getSelectedRow();

    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Select a product to delete");
        return;
    }

    int confirm = JOptionPane.showConfirmDialog(
        this,
        "Are you sure you want to delete this product?",
        "Confirm Delete",
        JOptionPane.YES_NO_OPTION
    );

    if (confirm != JOptionPane.YES_OPTION) return;

    int productId = (int) inventoryTable.getValueAt(row, 0);

    try {
        Connection conn = DBConnection.getConnection();
        String sql = "DELETE FROM inventory WHERE id=?";
        PreparedStatement pst = conn.prepareStatement(sql);

        pst.setInt(1, productId);
        pst.executeUpdate();
        conn.close();

        JOptionPane.showMessageDialog(this, "Product deleted!");
        loadInventoryData(); // 🔁 refresh

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Delete failed");
        e.printStackTrace();
    }    // TODO add your handling code here:
    }//GEN-LAST:event_deleteButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new InventoryFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton backButton;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JScrollPane inventoryScrollPane;
    private javax.swing.JTable inventoryTable;
    private javax.swing.JPanel navBarPanel;
    private javax.swing.JLabel sectionLabel;
    private javax.swing.JLabel titleLable;
    // End of variables declaration//GEN-END:variables
}
