/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Administrator
 */
import javax.swing.*;
import java.awt.*;

public class ServicesFrame extends JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ServicesFrame.class.getName());

    public ServicesFrame() {
        setTitle("Funeral Services");
        setSize(1000, 600);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        getContentPane().setLayout(null);

        setupServices();
    }

    private void setupServices() {
        // Main panel to hold cards
        JPanel mainPanel = new JPanel();
        mainPanel.setLayout(null); // manual positioning
        mainPanel.setBackground(Color.WHITE);
        mainPanel.setPreferredSize(new Dimension(950, 450));

        // Scroll pane
        JScrollPane scrollPane = new JScrollPane(mainPanel);
        scrollPane.setBounds(20, 80, 940, 450);
        scrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_NEVER);
        getContentPane().add(scrollPane);

        // Package cards
        int xPosition = 10;
        int cardWidth = 300;
        int cardHeight = 400;
        int spacing = 20;

        mainPanel.add(createPackageCard(
                "Basic Package",
                35000,
                "<html>• Simple Casket<br>• Embalming<br>• 9-Day Wake<br>• Basic Flowers<br>• Hearse (Burial Day)</html>",
                xPosition, 10, cardWidth, cardHeight
        ));

        xPosition += cardWidth + spacing;

        mainPanel.add(createPackageCard(
                "Standard Package",
                60000,
                "<html>• Mid-Range Casket<br>• Embalming + Cosmetic Care<br>• 9-Day Wake<br>• Decorated Flowers<br>• Tarpaulin<br>• Hearse + 1 Family Vehicle</html>",
                xPosition, 10, cardWidth, cardHeight
        ));

        xPosition += cardWidth + spacing;

        mainPanel.add(createPackageCard(
                "Premium Package",
                95000,
                "<html>• High-End Casket<br>• Professional Preparation<br>• 9-Day Wake<br>• Full Flower Setup<br>• Slideshow<br>• Hearse + 2 Vehicles<br>• Documentation Assistance</html>",
                xPosition, 10, cardWidth, cardHeight
        ));
    }

    private JPanel createPackageCard(String name, int price, String description, int x, int y, int width, int height) {
        JPanel panel = new JPanel();
        panel.setLayout(null);
        panel.setBackground(new Color(0, 153, 0)); // green
        panel.setBounds(x, y, width, height);
        panel.setBorder(BorderFactory.createLineBorder(Color.BLACK, 2));

        // Package name
        JLabel lblTitle = new JLabel(name, SwingConstants.CENTER);
        lblTitle.setFont(new Font("Arial", Font.BOLD, 18));
        lblTitle.setForeground(Color.WHITE);
        lblTitle.setBounds(10, 10, width - 20, 30);
        panel.add(lblTitle);

        // Description
        JLabel lblDesc = new JLabel(description);
        lblDesc.setFont(new Font("Arial", Font.PLAIN, 13));
        lblDesc.setForeground(Color.WHITE);
        lblDesc.setBounds(10, 50, width - 20, 250);
        panel.add(lblDesc);

        // Price
        JLabel lblPrice = new JLabel("₱" + String.format("%,d", price), SwingConstants.CENTER);
        lblPrice.setFont(new Font("Arial", Font.BOLD, 16));
        lblPrice.setForeground(Color.WHITE);
        lblPrice.setBounds(10, 310, width - 20, 30);
        panel.add(lblPrice);

        // Add to Cart button
        JButton btnAdd = new JButton("Add to Cart");
        btnAdd.setBackground(Color.WHITE);
        btnAdd.setForeground(new Color(0, 153, 0));
        btnAdd.setBounds(50, 350, width - 100, 30);
        btnAdd.addActionListener(e -> {
            // Use your existing Cart.add() method
            Cart.add(new Product(0, name, price));
            JOptionPane.showMessageDialog(this, name + " added to cart!");
        });
        panel.add(btnAdd);

        return panel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ServicesFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
